// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 16.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using DevExpress.CodedUIExtension.DXTestControls.v19_2;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod_Login - Use 'RecordedMethod_LoginParams' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod_Login()
        {
            #region Variable Declarations
            WinEdit uITextBox1Edit = this.UIForm1Window.UITextBox1Window.UITextBox1Edit;
            WinEdit uITextBox2Edit = this.UIForm1Window.UITextBox2Window.UITextBox2Edit;
            WinButton uIButton1Button = this.UIForm1Window.UIButton1Window.UIButton1Button;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            #endregion

            // Type '4' in 'textBox1' text box
            uITextBox1Edit.Text = this.RecordedMethod_LoginParams.UITextBox1EditText;

            // Type '5' in 'textBox2' text box
            uITextBox2Edit.Text = this.RecordedMethod_LoginParams.UITextBox2EditText;

            // Click 'button1' button
            Mouse.Click(uIButton1Button, new Point(81, 26));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(90, 13));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(25, 19));
        }
        
        /// <summary>
        /// RecordedMethod_LoginTest - Use 'RecordedMethod_LoginTestParams' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod_LoginTest()
        {
            #region Variable Declarations
            DXTextEdit uITxtNameEdit = this.UISignintoShopApplicatWindow.UITablePanel1Client.UITxtNameEdit;
            DXTextEdit uITxtPassEdit = this.UISignintoShopApplicatWindow.UITablePanel1Client.UITxtPassEdit;
            DXButton uILOGINButton = this.UISignintoShopApplicatWindow.UITablePanel1Client.UILOGINButton;
            DXTestControl uILOGOUTAccordionControlGroup = this.UIFormTNWindow.UIAccordionControlContAccordionControl.UILOGOUTAccordionControlGroup;
            WinButton uIYesButton = this.UILOGOUTWindow.UIYesWindow.UIYesButton;
            #endregion

            // Type 'taikhoan1' in 'txtName' text box
            //ValueAsString
            uITxtNameEdit.ValueAsString = this.RecordedMethod_LoginTestParams.UITxtNameEditValueAsString;

            // Type '******' in 'txtPass' text box
            //ValueAsString
            uITxtPassEdit.ValueAsString = this.RecordedMethod_LoginTestParams.UITxtPassEditValueAsString;

            // Click 'LOGIN' button
            Mouse.Click(uILOGINButton, new Point(1, 1));

            // Click 'LOG OUT' AccordionControlGroup
            Mouse.Click(uILOGOUTAccordionControlGroup, new Point(104, 23));

            // Click '&Yes' button
            Mouse.Click(uIYesButton, new Point(79, 20));
        }
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            DXTextEdit uITxtNameEdit = this.UISignintoShopApplicatWindow.UITablePanel1Client.UITxtNameEdit;
            DXTextEdit uITxtPassEdit = this.UISignintoShopApplicatWindow.UITablePanel1Client.UITxtPassEdit;
            DXCheckBox uICheckEdit1CheckBox = this.UISignintoShopApplicatWindow.UITablePanel1Client.UICheckEdit1CheckBox;
            DXButton uILOGINButton = this.UISignintoShopApplicatWindow.UITablePanel1Client.UILOGINButton;
            DXTestControl uILOGOUTAccordionControlGroup = this.UIFormTNWindow.UIAccordionControlContAccordionControl.UILOGOUTAccordionControlGroup;
            WinButton uIYesButton = this.UILOGOUTWindow.UIYesWindow.UIYesButton;
            #endregion

            // Type 'taikhoan1' in 'txtName' text box
            //ValueAsString
            uITxtNameEdit.ValueAsString = this.RecordedMethod1Params.UITxtNameEditValueAsString;

            // Type '{Tab}' in 'txtName' text box
            Keyboard.SendKeys(uITxtNameEdit, this.RecordedMethod1Params.UITxtNameEditSendKeys, ModifierKeys.None);

            // Type '******' in 'txtPass' text box
            //ValueAsString
            uITxtPassEdit.ValueAsString = this.RecordedMethod1Params.UITxtPassEditValueAsString;

            // Clear 'checkEdit1' check box
            uICheckEdit1CheckBox.Checked = this.RecordedMethod1Params.UICheckEdit1CheckBoxChecked;

            // Type '123456' in 'txtPass' text box
            //ValueAsString
            uITxtPassEdit.ValueAsString = this.RecordedMethod1Params.UITxtPassEditValueAsString1;

            // Click 'LOGIN' button
            Mouse.Click(uILOGINButton, new Point(1, 1));

            // Click 'LOG OUT' AccordionControlGroup
            Mouse.Click(uILOGOUTAccordionControlGroup, new Point(96, 32));

            // Click '&Yes' button
            Mouse.Click(uIYesButton, new Point(31, 9));
        }
        
        /// <summary>
        /// Trường hợp 1: Nhập liệu không hợp lệ
        /// </summary>
        public void TC_Login_01()
        {
            #region Variable Declarations
            DXTextEdit uITxtNameEdit = this.UISignintoShopApplicatWindow.UITablePanel1Client.UITxtNameEdit;
            DXTextEdit uITxtPassEdit = this.UISignintoShopApplicatWindow.UITablePanel1Client.UITxtPassEdit;
            DXCheckBox uICheckEdit1CheckBox = this.UISignintoShopApplicatWindow.UITablePanel1Client.UICheckEdit1CheckBox;
            DXButton uILOGINButton = this.UISignintoShopApplicatWindow.UITablePanel1Client.UILOGINButton;
            WinButton uIOKButton = this.UIERRORWindow.UIOKWindow.UIOKButton;
            #endregion

            // Type '123' in 'txtName' text box
            //ValueAsString
            uITxtNameEdit.ValueAsString = this.TC_Login_01Params.UITxtNameEditValueAsString;

            // Type '***' in 'txtPass' text box
            //ValueAsString
            uITxtPassEdit.ValueAsString = this.TC_Login_01Params.UITxtPassEditValueAsString;

            // Clear 'checkEdit1' check box
            uICheckEdit1CheckBox.Checked = this.TC_Login_01Params.UICheckEdit1CheckBoxChecked;

            // Click 'LOGIN' button
            Mouse.Click(uILOGINButton, new Point(1, 1));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(44, 19));
        }
        
        /// <summary>
        /// Trường hợp 2: Nhập đúng tên tài khoản
        /// </summary>
        public void TC_Login_02()
        {
            #region Variable Declarations
            DXTextEdit uITxtNameEdit = this.UISignintoShopApplicatWindow.UITablePanel1Client.UITxtNameEdit;
            DXTextEdit uITxtPassEdit = this.UISignintoShopApplicatWindow.UITablePanel1Client.UITxtPassEdit;
            DXCheckBox uICheckEdit1CheckBox = this.UISignintoShopApplicatWindow.UITablePanel1Client.UICheckEdit1CheckBox;
            DXButton uILOGINButton = this.UISignintoShopApplicatWindow.UITablePanel1Client.UILOGINButton;
            WinButton uIOKButton = this.UIERRORWindow.UIOKWindow.UIOKButton;
            #endregion

            // Type 'taikhoan1' in 'txtName' text box
            //ValueAsString
            uITxtNameEdit.ValueAsString = this.TC_Login_02Params.UITxtNameEditValueAsString;

            // Type '***' in 'txtPass' text box
            //ValueAsString
            uITxtPassEdit.ValueAsString = this.TC_Login_02Params.UITxtPassEditValueAsString;

            // Select 'checkEdit1' check box
            uICheckEdit1CheckBox.Checked = this.TC_Login_02Params.UICheckEdit1CheckBoxChecked;

            // Click 'LOGIN' button
            Mouse.Click(uILOGINButton, new Point(1, 1));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(63, 27));
        }
        
        /// <summary>
        /// Trường hợp 3: Nhập đúng mật khẩu
        /// </summary>
        public void TC_Login_03()
        {
            #region Variable Declarations
            DXTextEdit uITxtNameEdit = this.UISignintoShopApplicatWindow.UITablePanel1Client.UITxtNameEdit;
            DXTextEdit uITxtPassEdit = this.UISignintoShopApplicatWindow.UITablePanel1Client.UITxtPassEdit;
            DXCheckBox uICheckEdit1CheckBox = this.UISignintoShopApplicatWindow.UITablePanel1Client.UICheckEdit1CheckBox;
            DXButton uILOGINButton = this.UISignintoShopApplicatWindow.UITablePanel1Client.UILOGINButton;
            WinButton uIOKButton = this.UIERRORWindow.UIOKWindow.UIOKButton;
            #endregion

            // Type 'taikhoan1000' in 'txtName' text box
            //ValueAsString
            uITxtNameEdit.ValueAsString = this.TC_Login_03Params.UITxtNameEditValueAsString;

            // Type '******' in 'txtPass' text box
            //ValueAsString
            uITxtPassEdit.ValueAsString = this.TC_Login_03Params.UITxtPassEditValueAsString;

            // Select 'checkEdit1' check box
            uICheckEdit1CheckBox.Checked = this.TC_Login_03Params.UICheckEdit1CheckBoxChecked;

            // Click 'LOGIN' button
            Mouse.Click(uILOGINButton, new Point(1, 1));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(38, 31));
        }
        
        /// <summary>
        /// Trường hợp 4: Đăng nhập thành công
        /// </summary>
        public void TC_Login_04()
        {
            #region Variable Declarations
            DXTextEdit uITxtNameEdit = this.UISignintoShopApplicatWindow.UITablePanel1Client.UITxtNameEdit;
            DXTextEdit uITxtPassEdit = this.UISignintoShopApplicatWindow.UITablePanel1Client.UITxtPassEdit;
            DXCheckBox uICheckEdit1CheckBox = this.UISignintoShopApplicatWindow.UITablePanel1Client.UICheckEdit1CheckBox;
            DXButton uILOGINButton = this.UISignintoShopApplicatWindow.UITablePanel1Client.UILOGINButton;
            DXTestControl uILOGOUTAccordionControlGroup = this.UIFormTNWindow.UIAccordionControlContAccordionControl.UILOGOUTAccordionControlGroup;
            WinButton uIYesButton = this.UILOGOUTWindow.UIYesWindow.UIYesButton;
            #endregion

            // Type 'taikhoan1' in 'txtName' text box
            //ValueAsString
            uITxtNameEdit.ValueAsString = this.TC_Login_04Params.UITxtNameEditValueAsString;

            // Type '******' in 'txtPass' text box
            //ValueAsString
            uITxtPassEdit.ValueAsString = this.TC_Login_04Params.UITxtPassEditValueAsString;

            // Select 'checkEdit1' check box
            uICheckEdit1CheckBox.Checked = this.TC_Login_04Params.UICheckEdit1CheckBoxChecked;

            // Click 'LOGIN' button
            Mouse.Click(uILOGINButton, new Point(1, 1));

            // Click 'LOG OUT' AccordionControlGroup
            Mouse.Click(uILOGOUTAccordionControlGroup, new Point(113, 18));

            // Click '&Yes' button
            Mouse.Click(uIYesButton, new Point(81, 21));
        }
        
        /// <summary>
        /// RecordedMethod2 - Use 'RecordedMethod2Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            DXTextEdit uITxtNameEdit = this.UISignintoShopApplicatWindow.UITablePanel1Client.UITxtNameEdit;
            DXTextEdit uITxtPassEdit = this.UISignintoShopApplicatWindow.UITablePanel1Client.UITxtPassEdit;
            DXButton uILOGINButton = this.UISignintoShopApplicatWindow.UITablePanel1Client.UILOGINButton;
            DXTestControl uILOGOUTAccordionControlGroup = this.UIFormTNWindow.UIAccordionControlContAccordionControl.UILOGOUTAccordionControlGroup;
            WinButton uIYesButton = this.UILOGOUTWindow.UIYesWindow.UIYesButton;
            #endregion

            // Type 'taikhoan1' in 'txtName' text box
            //ValueAsString
            uITxtNameEdit.ValueAsString = this.RecordedMethod2Params.UITxtNameEditValueAsString;

            // Type '******' in 'txtPass' text box
            //ValueAsString
            uITxtPassEdit.ValueAsString = this.RecordedMethod2Params.UITxtPassEditValueAsString;

            // Click 'LOGIN' button
            Mouse.Click(uILOGINButton, new Point(1, 1));

            // Click 'LOG OUT' AccordionControlGroup
            Mouse.Click(uILOGOUTAccordionControlGroup, new Point(73, 28));

            // Click '&Yes' button
            Mouse.Click(uIYesButton, new Point(96, 25));
        }
        
        /// <summary>
        /// Trường hợp 1 : Nhập liệu không hợp lệ
        /// </summary>
        public void TC_Forget_01()
        {
            #region Variable Declarations
            DXTextEdit uITxtNameEdit = this.UIFormForgetWindow.UITablePanel1Client.UITxtNameEdit;
            DXTextEdit uITxtPhoneEdit = this.UIFormForgetWindow.UITablePanel1Client.UITxtPhoneEdit;
            DXTextEdit uITxtEmailEdit = this.UIFormForgetWindow.UITablePanel1Client.UITxtEmailEdit;
            DXButton uIAcceptButton = this.UIFormForgetWindow.UITablePanel1Client.UIAcceptButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            #endregion

            // Type '123' in 'txtName' text box
            //ValueAsString
            uITxtNameEdit.ValueAsString = this.TC_Forget_01Params.UITxtNameEditValueAsString;

            // Type '123@yahoo.com' in 'txtPhone' text box
            //ValueAsString
            uITxtPhoneEdit.ValueAsString = this.TC_Forget_01Params.UITxtPhoneEditValueAsString;

            // Type '1236' in 'txtEmail' text box
            //ValueAsString
            uITxtEmailEdit.ValueAsString = this.TC_Forget_01Params.UITxtEmailEditValueAsString;

            // Click 'Accept' button
            Mouse.Click(uIAcceptButton, new Point(1, 1));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(53, 23));
        }
        
        /// <summary>
        /// Trường hợp 02: Nhập đúng tên tài khoản
        /// </summary>
        public void TC_Forget_02()
        {
            #region Variable Declarations
            DXTextEdit uITxtNameEdit = this.UIFormForgetWindow.UITablePanel1Client.UITxtNameEdit;
            DXTextEdit uITxtPhoneEdit = this.UIFormForgetWindow.UITablePanel1Client.UITxtPhoneEdit;
            DXTextEdit uITxtEmailEdit = this.UIFormForgetWindow.UITablePanel1Client.UITxtEmailEdit;
            DXButton uIAcceptButton = this.UIFormForgetWindow.UITablePanel1Client.UIAcceptButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            #endregion

            // Type 'taikhoan' in 'txtName' text box
            //ValueAsString
            uITxtNameEdit.ValueAsString = this.TC_Forget_02Params.UITxtNameEditValueAsString;

            // Type '{Tab}' in 'txtName' text box
            Keyboard.SendKeys(uITxtNameEdit, this.TC_Forget_02Params.UITxtNameEditSendKeys, ModifierKeys.None);

            // Type 'taikhoan1' in 'txtName' text box
            //ValueAsString
            uITxtNameEdit.ValueAsString = this.TC_Forget_02Params.UITxtNameEditValueAsString1;

            // Type '123@yahoo.com' in 'txtPhone' text box
            //ValueAsString
            uITxtPhoneEdit.ValueAsString = this.TC_Forget_02Params.UITxtPhoneEditValueAsString;

            // Type '2341' in 'txtEmail' text box
            //ValueAsString
            uITxtEmailEdit.ValueAsString = this.TC_Forget_02Params.UITxtEmailEditValueAsString;

            // Click 'Accept' button
            Mouse.Click(uIAcceptButton, new Point(1, 1));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(94, 24));
        }
        
        /// <summary>
        /// Trường hợp 3: Nhập đúng Email
        /// </summary>
        public void TC_Forget_03()
        {
            #region Variable Declarations
            DXTextEdit uITxtNameEdit = this.UIFormForgetWindow.UITablePanel1Client.UITxtNameEdit;
            DXTextEdit uITxtPhoneEdit = this.UIFormForgetWindow.UITablePanel1Client.UITxtPhoneEdit;
            DXTextEdit uITxtEmailEdit = this.UIFormForgetWindow.UITablePanel1Client.UITxtEmailEdit;
            DXButton uIAcceptButton = this.UIFormForgetWindow.UITablePanel1Client.UIAcceptButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            DXTestControl uITablePanel1Client = this.UIFormForgetWindow.UITablePanel1Client;
            #endregion

            // Type 'taikhoan100' in 'txtName' text box
            //ValueAsString
            uITxtNameEdit.ValueAsString = this.TC_Forget_03Params.UITxtNameEditValueAsString;

            // Type '123456' in 'txtPhone' text box
            //ValueAsString
            uITxtPhoneEdit.ValueAsString = this.TC_Forget_03Params.UITxtPhoneEditValueAsString;

            // Type '2341' in 'txtEmail' text box
            //ValueAsString
            uITxtEmailEdit.ValueAsString = this.TC_Forget_03Params.UITxtEmailEditValueAsString;

            // Click 'Accept' button
            Mouse.Click(uIAcceptButton, new Point(1, 1));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(62, 19));

            // Type 'taikhoan100' in 'txtName' text box
            //ValueAsString
            uITxtNameEdit.ValueAsString = this.TC_Forget_03Params.UITxtNameEditValueAsString1;

            // Click 'tablePanel1' client
            Mouse.Click(uITablePanel1Client, new Point(714, 311));

            // Type 'loan123@gmail.com' in 'txtPhone' text box
            //ValueAsString
            uITxtPhoneEdit.ValueAsString = this.TC_Forget_03Params.UITxtPhoneEditValueAsString1;

            // Type '2341' in 'txtEmail' text box
            //ValueAsString
            uITxtEmailEdit.ValueAsString = this.TC_Forget_03Params.UITxtEmailEditValueAsString1;

            // Click 'Accept' button
            Mouse.Click(uIAcceptButton, new Point(1, 1));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(58, 7));
        }
        
        /// <summary>
        /// Trường hợp 4 : Nhập đúng số điện thoại
        /// </summary>
        public void TC_Forget_04()
        {
            #region Variable Declarations
            DXTextEdit uITxtNameEdit = this.UIFormForgetWindow.UITablePanel1Client.UITxtNameEdit;
            DXTextEdit uITxtPhoneEdit = this.UIFormForgetWindow.UITablePanel1Client.UITxtPhoneEdit;
            DXTextEdit uITxtEmailEdit = this.UIFormForgetWindow.UITablePanel1Client.UITxtEmailEdit;
            DXButton uIAcceptButton = this.UIFormForgetWindow.UITablePanel1Client.UIAcceptButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            #endregion

            // Type 'taikhoan1' in 'txtName' text box
            //ValueAsString
            uITxtNameEdit.ValueAsString = this.TC_Forget_04Params.UITxtNameEditValueAsString;

            // Type '123' in 'txtPhone' text box
            //ValueAsString
            uITxtPhoneEdit.ValueAsString = this.TC_Forget_04Params.UITxtPhoneEditValueAsString;

            // Type '0911119222' in 'txtEmail' text box
            //ValueAsString
            uITxtEmailEdit.ValueAsString = this.TC_Forget_04Params.UITxtEmailEditValueAsString;

            // Click 'Accept' button
            Mouse.Click(uIAcceptButton, new Point(1, 1));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(75, 19));
        }
        
        /// <summary>
        /// Tìm  mật khẩu thành công
        /// </summary>
        public void TC_Forget_05()
        {
            #region Variable Declarations
            DXTextEdit uITxtNameEdit = this.UIFormForgetWindow.UITablePanel1Client.UITxtNameEdit;
            DXTextEdit uITxtPhoneEdit = this.UIFormForgetWindow.UITablePanel1Client.UITxtPhoneEdit;
            DXTextEdit uITxtEmailEdit = this.UIFormForgetWindow.UITablePanel1Client.UITxtEmailEdit;
            DXButton uIAcceptButton = this.UIFormForgetWindow.UITablePanel1Client.UIAcceptButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            DXTestControl uILbPassLabel = this.UIFormForgetWindow.UITablePanel1Client.UILbPassLabel;
            #endregion

            // Type 'taikhoan1' in 'txtName' text box
            //ValueAsString
            uITxtNameEdit.ValueAsString = this.TC_Forget_05Params.UITxtNameEditValueAsString;

            // Type '0911119222' in 'txtPhone' text box
            //ValueAsString
            uITxtPhoneEdit.ValueAsString = this.TC_Forget_05Params.UITxtPhoneEditValueAsString;

            // Type 'loan123@gmail.com' in 'txtEmail' text box
            //ValueAsString
            uITxtEmailEdit.ValueAsString = this.TC_Forget_05Params.UITxtEmailEditValueAsString;

            // Click 'Accept' button
            Mouse.Click(uIAcceptButton, new Point(1, 1));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(76, 16));

            // Type 'taikhoan1' in 'txtName' text box
            //ValueAsString
            uITxtNameEdit.ValueAsString = this.TC_Forget_05Params.UITxtNameEditValueAsString1;

            // Type 'hong123@gmail.com' in 'txtPhone' text box
            //ValueAsString
            uITxtPhoneEdit.ValueAsString = this.TC_Forget_05Params.UITxtPhoneEditValueAsString1;

            // Type 'hong123@gmail.com' in 'txtEmail' text box
            //ValueAsString
            uITxtEmailEdit.ValueAsString = this.TC_Forget_05Params.UITxtEmailEditValueAsString1;

            // Type '0912637381' in 'txtPhone' text box
            //ValueAsString
            uITxtPhoneEdit.ValueAsString = this.TC_Forget_05Params.UITxtPhoneEditValueAsString2;

            // Click 'Accept' button
            Mouse.Click(uIAcceptButton, new Point(1, 1));

            // Move 'lbPass' label
            Mouse.StartDragging(uILbPassLabel, new Point(129, 16));
            Mouse.StopDragging(uILbPassLabel, 50, 8);

            // Move 'lbPass' label
            Mouse.StartDragging(uILbPassLabel, new Point(108, 19));
            Mouse.StopDragging(uILbPassLabel, 43, 2);

            // Double-Click 'lbPass' label
            Mouse.DoubleClick(uILbPassLabel, new Point(85, 30));

            // Click 'lbPass' label
            Mouse.Click(uILbPassLabel, new Point(79, 30));
        }
        
        /// <summary>
        /// RecordedMethod3 - Use 'RecordedMethod3Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod3()
        {
            #region Variable Declarations
            DXTextEdit uITxtNameEdit = this.UISignintoShopApplicatWindow.UITablePanel1Client.UITxtNameEdit;
            DXTextEdit uITxtPassEdit = this.UISignintoShopApplicatWindow.UITablePanel1Client.UITxtPassEdit;
            DXCheckBox uICheckEdit1CheckBox = this.UISignintoShopApplicatWindow.UITablePanel1Client.UICheckEdit1CheckBox;
            DXButton uILOGINButton = this.UISignintoShopApplicatWindow.UITablePanel1Client.UILOGINButton;
            DXTestControl uILOGOUTAccordionControlGroup = this.UIFormTNWindow.UIAccordionControlContAccordionControl.UILOGOUTAccordionControlGroup;
            WinButton uIYesButton = this.UILOGOUTWindow.UIYesWindow.UIYesButton;
            #endregion

            // Type 'taikhoan1' in 'txtName' text box
            //ValueAsString
            uITxtNameEdit.ValueAsString = this.RecordedMethod3Params.UITxtNameEditValueAsString;

            // Type '******' in 'txtPass' text box
            //ValueAsString
            uITxtPassEdit.ValueAsString = this.RecordedMethod3Params.UITxtPassEditValueAsString;

            // Select 'checkEdit1' check box
            uICheckEdit1CheckBox.Checked = this.RecordedMethod3Params.UICheckEdit1CheckBoxChecked;

            // Click 'LOGIN' button
            Mouse.Click(uILOGINButton, new Point(1, 1));

            // Click 'LOG OUT' AccordionControlGroup
            Mouse.Click(uILOGOUTAccordionControlGroup, new Point(88, 16));

            // Click '&Yes' button
            Mouse.Click(uIYesButton, new Point(76, 24));
        }
        
        #region Properties
        public virtual RecordedMethod_LoginParams RecordedMethod_LoginParams
        {
            get
            {
                if ((this.mRecordedMethod_LoginParams == null))
                {
                    this.mRecordedMethod_LoginParams = new RecordedMethod_LoginParams();
                }
                return this.mRecordedMethod_LoginParams;
            }
        }
        
        public virtual RecordedMethod_LoginTestParams RecordedMethod_LoginTestParams
        {
            get
            {
                if ((this.mRecordedMethod_LoginTestParams == null))
                {
                    this.mRecordedMethod_LoginTestParams = new RecordedMethod_LoginTestParams();
                }
                return this.mRecordedMethod_LoginTestParams;
            }
        }
        
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public virtual TC_Login_01Params TC_Login_01Params
        {
            get
            {
                if ((this.mTC_Login_01Params == null))
                {
                    this.mTC_Login_01Params = new TC_Login_01Params();
                }
                return this.mTC_Login_01Params;
            }
        }
        
        public virtual TC_Login_02Params TC_Login_02Params
        {
            get
            {
                if ((this.mTC_Login_02Params == null))
                {
                    this.mTC_Login_02Params = new TC_Login_02Params();
                }
                return this.mTC_Login_02Params;
            }
        }
        
        public virtual TC_Login_03Params TC_Login_03Params
        {
            get
            {
                if ((this.mTC_Login_03Params == null))
                {
                    this.mTC_Login_03Params = new TC_Login_03Params();
                }
                return this.mTC_Login_03Params;
            }
        }
        
        public virtual TC_Login_04Params TC_Login_04Params
        {
            get
            {
                if ((this.mTC_Login_04Params == null))
                {
                    this.mTC_Login_04Params = new TC_Login_04Params();
                }
                return this.mTC_Login_04Params;
            }
        }
        
        public virtual RecordedMethod2Params RecordedMethod2Params
        {
            get
            {
                if ((this.mRecordedMethod2Params == null))
                {
                    this.mRecordedMethod2Params = new RecordedMethod2Params();
                }
                return this.mRecordedMethod2Params;
            }
        }
        
        public virtual TC_Forget_01Params TC_Forget_01Params
        {
            get
            {
                if ((this.mTC_Forget_01Params == null))
                {
                    this.mTC_Forget_01Params = new TC_Forget_01Params();
                }
                return this.mTC_Forget_01Params;
            }
        }
        
        public virtual TC_Forget_02Params TC_Forget_02Params
        {
            get
            {
                if ((this.mTC_Forget_02Params == null))
                {
                    this.mTC_Forget_02Params = new TC_Forget_02Params();
                }
                return this.mTC_Forget_02Params;
            }
        }
        
        public virtual TC_Forget_03Params TC_Forget_03Params
        {
            get
            {
                if ((this.mTC_Forget_03Params == null))
                {
                    this.mTC_Forget_03Params = new TC_Forget_03Params();
                }
                return this.mTC_Forget_03Params;
            }
        }
        
        public virtual TC_Forget_04Params TC_Forget_04Params
        {
            get
            {
                if ((this.mTC_Forget_04Params == null))
                {
                    this.mTC_Forget_04Params = new TC_Forget_04Params();
                }
                return this.mTC_Forget_04Params;
            }
        }
        
        public virtual TC_Forget_05Params TC_Forget_05Params
        {
            get
            {
                if ((this.mTC_Forget_05Params == null))
                {
                    this.mTC_Forget_05Params = new TC_Forget_05Params();
                }
                return this.mTC_Forget_05Params;
            }
        }
        
        public virtual RecordedMethod3Params RecordedMethod3Params
        {
            get
            {
                if ((this.mRecordedMethod3Params == null))
                {
                    this.mRecordedMethod3Params = new RecordedMethod3Params();
                }
                return this.mRecordedMethod3Params;
            }
        }
        
        public UIXtraForm1Window UIXtraForm1Window
        {
            get
            {
                if ((this.mUIXtraForm1Window == null))
                {
                    this.mUIXtraForm1Window = new UIXtraForm1Window();
                }
                return this.mUIXtraForm1Window;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow();
                }
                return this.mUIOKWindow;
            }
        }
        
        public UIForm1Window UIForm1Window
        {
            get
            {
                if ((this.mUIForm1Window == null))
                {
                    this.mUIForm1Window = new UIForm1Window();
                }
                return this.mUIForm1Window;
            }
        }
        
        public UISignintoShopApplicatWindow UISignintoShopApplicatWindow
        {
            get
            {
                if ((this.mUISignintoShopApplicatWindow == null))
                {
                    this.mUISignintoShopApplicatWindow = new UISignintoShopApplicatWindow();
                }
                return this.mUISignintoShopApplicatWindow;
            }
        }
        
        public UINhom8_KDPM_PhanMemQuWindow UINhom8_KDPM_PhanMemQuWindow
        {
            get
            {
                if ((this.mUINhom8_KDPM_PhanMemQuWindow == null))
                {
                    this.mUINhom8_KDPM_PhanMemQuWindow = new UINhom8_KDPM_PhanMemQuWindow();
                }
                return this.mUINhom8_KDPM_PhanMemQuWindow;
            }
        }
        
        public UIFormTNWindow UIFormTNWindow
        {
            get
            {
                if ((this.mUIFormTNWindow == null))
                {
                    this.mUIFormTNWindow = new UIFormTNWindow();
                }
                return this.mUIFormTNWindow;
            }
        }
        
        public UILOGOUTWindow UILOGOUTWindow
        {
            get
            {
                if ((this.mUILOGOUTWindow == null))
                {
                    this.mUILOGOUTWindow = new UILOGOUTWindow();
                }
                return this.mUILOGOUTWindow;
            }
        }
        
        public UIERRORWindow UIERRORWindow
        {
            get
            {
                if ((this.mUIERRORWindow == null))
                {
                    this.mUIERRORWindow = new UIERRORWindow();
                }
                return this.mUIERRORWindow;
            }
        }
        
        public UIChàomừngWindow UIChàomừngWindow
        {
            get
            {
                if ((this.mUIChàomừngWindow == null))
                {
                    this.mUIChàomừngWindow = new UIChàomừngWindow();
                }
                return this.mUIChàomừngWindow;
            }
        }
        
        public UIFormForgetWindow UIFormForgetWindow
        {
            get
            {
                if ((this.mUIFormForgetWindow == null))
                {
                    this.mUIFormForgetWindow = new UIFormForgetWindow();
                }
                return this.mUIFormForgetWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod_LoginParams mRecordedMethod_LoginParams;
        
        private RecordedMethod_LoginTestParams mRecordedMethod_LoginTestParams;
        
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private TC_Login_01Params mTC_Login_01Params;
        
        private TC_Login_02Params mTC_Login_02Params;
        
        private TC_Login_03Params mTC_Login_03Params;
        
        private TC_Login_04Params mTC_Login_04Params;
        
        private RecordedMethod2Params mRecordedMethod2Params;
        
        private TC_Forget_01Params mTC_Forget_01Params;
        
        private TC_Forget_02Params mTC_Forget_02Params;
        
        private TC_Forget_03Params mTC_Forget_03Params;
        
        private TC_Forget_04Params mTC_Forget_04Params;
        
        private TC_Forget_05Params mTC_Forget_05Params;
        
        private RecordedMethod3Params mRecordedMethod3Params;
        
        private UIXtraForm1Window mUIXtraForm1Window;
        
        private UIItemWindow mUIItemWindow;
        
        private UIOKWindow mUIOKWindow;
        
        private UIForm1Window mUIForm1Window;
        
        private UISignintoShopApplicatWindow mUISignintoShopApplicatWindow;
        
        private UINhom8_KDPM_PhanMemQuWindow mUINhom8_KDPM_PhanMemQuWindow;
        
        private UIFormTNWindow mUIFormTNWindow;
        
        private UILOGOUTWindow mUILOGOUTWindow;
        
        private UIERRORWindow mUIERRORWindow;
        
        private UIChàomừngWindow mUIChàomừngWindow;
        
        private UIFormForgetWindow mUIFormForgetWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod_Login'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class RecordedMethod_LoginParams
    {
        
        #region Fields
        /// <summary>
        /// Type '4' in 'textBox1' text box
        /// </summary>
        public string UITextBox1EditText = "4";
        
        /// <summary>
        /// Type '5' in 'textBox2' text box
        /// </summary>
        public string UITextBox2EditText = "5";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod_LoginTest'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class RecordedMethod_LoginTestParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'taikhoan1' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditValueAsString = "taikhoan1";
        
        /// <summary>
        /// Type '******' in 'txtPass' text box
        /// </summary>
        public string UITxtPassEditValueAsString = "******";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'taikhoan1' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditValueAsString = "taikhoan1";
        
        /// <summary>
        /// Type '{Tab}' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '******' in 'txtPass' text box
        /// </summary>
        public string UITxtPassEditValueAsString = "******";
        
        /// <summary>
        /// Clear 'checkEdit1' check box
        /// </summary>
        public bool UICheckEdit1CheckBoxChecked = false;
        
        /// <summary>
        /// Type '123456' in 'txtPass' text box
        /// </summary>
        public string UITxtPassEditValueAsString1 = "123456";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TC_Login_01'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class TC_Login_01Params
    {
        
        #region Fields
        /// <summary>
        /// Type '123' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditValueAsString = "123";
        
        /// <summary>
        /// Type '***' in 'txtPass' text box
        /// </summary>
        public string UITxtPassEditValueAsString = "***";
        
        /// <summary>
        /// Clear 'checkEdit1' check box
        /// </summary>
        public bool UICheckEdit1CheckBoxChecked = false;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TC_Login_02'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class TC_Login_02Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'taikhoan1' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditValueAsString = "taikhoan1";
        
        /// <summary>
        /// Type '***' in 'txtPass' text box
        /// </summary>
        public string UITxtPassEditValueAsString = "***";
        
        /// <summary>
        /// Select 'checkEdit1' check box
        /// </summary>
        public bool UICheckEdit1CheckBoxChecked = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TC_Login_03'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class TC_Login_03Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'taikhoan1000' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditValueAsString = "taikhoan1000";
        
        /// <summary>
        /// Type '******' in 'txtPass' text box
        /// </summary>
        public string UITxtPassEditValueAsString = "******";
        
        /// <summary>
        /// Select 'checkEdit1' check box
        /// </summary>
        public bool UICheckEdit1CheckBoxChecked = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TC_Login_04'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class TC_Login_04Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'taikhoan1' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditValueAsString = "taikhoan1";
        
        /// <summary>
        /// Type '******' in 'txtPass' text box
        /// </summary>
        public string UITxtPassEditValueAsString = "******";
        
        /// <summary>
        /// Select 'checkEdit1' check box
        /// </summary>
        public bool UICheckEdit1CheckBoxChecked = true;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class RecordedMethod2Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'taikhoan1' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditValueAsString = "taikhoan1";
        
        /// <summary>
        /// Type '******' in 'txtPass' text box
        /// </summary>
        public string UITxtPassEditValueAsString = "******";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TC_Forget_01'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class TC_Forget_01Params
    {
        
        #region Fields
        /// <summary>
        /// Type '123' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditValueAsString = "123";
        
        /// <summary>
        /// Type '123@yahoo.com' in 'txtPhone' text box
        /// </summary>
        public string UITxtPhoneEditValueAsString = "123@yahoo.com";
        
        /// <summary>
        /// Type '1236' in 'txtEmail' text box
        /// </summary>
        public string UITxtEmailEditValueAsString = "1236";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TC_Forget_02'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class TC_Forget_02Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'taikhoan' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditValueAsString = "taikhoan";
        
        /// <summary>
        /// Type '{Tab}' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'taikhoan1' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditValueAsString1 = "taikhoan1";
        
        /// <summary>
        /// Type '123@yahoo.com' in 'txtPhone' text box
        /// </summary>
        public string UITxtPhoneEditValueAsString = "123@yahoo.com";
        
        /// <summary>
        /// Type '2341' in 'txtEmail' text box
        /// </summary>
        public string UITxtEmailEditValueAsString = "2341";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TC_Forget_03'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class TC_Forget_03Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'taikhoan100' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditValueAsString = "taikhoan100";
        
        /// <summary>
        /// Type '123456' in 'txtPhone' text box
        /// </summary>
        public string UITxtPhoneEditValueAsString = "123456";
        
        /// <summary>
        /// Type '2341' in 'txtEmail' text box
        /// </summary>
        public string UITxtEmailEditValueAsString = "2341";
        
        /// <summary>
        /// Type 'taikhoan100' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditValueAsString1 = "taikhoan100";
        
        /// <summary>
        /// Type 'loan123@gmail.com' in 'txtPhone' text box
        /// </summary>
        public string UITxtPhoneEditValueAsString1 = "loan123@gmail.com";
        
        /// <summary>
        /// Type '2341' in 'txtEmail' text box
        /// </summary>
        public string UITxtEmailEditValueAsString1 = "2341";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TC_Forget_04'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class TC_Forget_04Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'taikhoan1' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditValueAsString = "taikhoan1";
        
        /// <summary>
        /// Type '123' in 'txtPhone' text box
        /// </summary>
        public string UITxtPhoneEditValueAsString = "123";
        
        /// <summary>
        /// Type '0911119222' in 'txtEmail' text box
        /// </summary>
        public string UITxtEmailEditValueAsString = "0911119222";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TC_Forget_05'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class TC_Forget_05Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'taikhoan1' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditValueAsString = "taikhoan1";
        
        /// <summary>
        /// Type '0911119222' in 'txtPhone' text box
        /// </summary>
        public string UITxtPhoneEditValueAsString = "0911119222";
        
        /// <summary>
        /// Type 'loan123@gmail.com' in 'txtEmail' text box
        /// </summary>
        public string UITxtEmailEditValueAsString = "loan123@gmail.com";
        
        /// <summary>
        /// Type 'taikhoan1' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditValueAsString1 = "taikhoan1";
        
        /// <summary>
        /// Type 'hong123@gmail.com' in 'txtPhone' text box
        /// </summary>
        public string UITxtPhoneEditValueAsString1 = "hong123@gmail.com";
        
        /// <summary>
        /// Type 'hong123@gmail.com' in 'txtEmail' text box
        /// </summary>
        public string UITxtEmailEditValueAsString1 = "hong123@gmail.com";
        
        /// <summary>
        /// Type '0912637381' in 'txtPhone' text box
        /// </summary>
        public string UITxtPhoneEditValueAsString2 = "0912637381";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod3'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class RecordedMethod3Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'taikhoan1' in 'txtName' text box
        /// </summary>
        public string UITxtNameEditValueAsString = "taikhoan1";
        
        /// <summary>
        /// Type '******' in 'txtPass' text box
        /// </summary>
        public string UITxtPassEditValueAsString = "******";
        
        /// <summary>
        /// Select 'checkEdit1' check box
        /// </summary>
        public bool UICheckEdit1CheckBoxChecked = true;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIXtraForm1Window : WinWindow
    {
        
        public UIXtraForm1Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "XtraForm1";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("XtraForm1");
            #endregion
        }
        
        #region Properties
        public UITablePanel1Client UITablePanel1Client
        {
            get
            {
                if ((this.mUITablePanel1Client == null))
                {
                    this.mUITablePanel1Client = new UITablePanel1Client(this);
                }
                return this.mUITablePanel1Client;
            }
        }
        
        public WinEdit UITextBox1Edit
        {
            get
            {
                if ((this.mUITextBox1Edit == null))
                {
                    this.mUITextBox1Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITextBox1Edit.WindowTitles.Add("XtraForm1");
                    #endregion
                }
                return this.mUITextBox1Edit;
            }
        }
        
        public WinEdit UITextBox2Edit
        {
            get
            {
                if ((this.mUITextBox2Edit == null))
                {
                    this.mUITextBox2Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITextBox2Edit.WindowTitles.Add("XtraForm1");
                    #endregion
                }
                return this.mUITextBox2Edit;
            }
        }
        #endregion
        
        #region Fields
        private UITablePanel1Client mUITablePanel1Client;
        
        private WinEdit mUITextBox1Edit;
        
        private WinEdit mUITextBox2Edit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UITablePanel1Client : DXTestControl
    {
        
        public UITablePanel1Client(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "tablePanel1";
            this.SearchProperties[DXTestControl.PropertyNames.ClassName] = "TablePanel";
            this.WindowTitles.Add("XtraForm1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBox1Edit
        {
            get
            {
                if ((this.mUITextBox1Edit == null))
                {
                    this.mUITextBox1Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITextBox1Edit.WindowTitles.Add("XtraForm1");
                    #endregion
                }
                return this.mUITextBox1Edit;
            }
        }
        
        public WinEdit UITextBox2Edit
        {
            get
            {
                if ((this.mUITextBox2Edit == null))
                {
                    this.mUITextBox2Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITextBox2Edit.WindowTitles.Add("XtraForm1");
                    #endregion
                }
                return this.mUITextBox2Edit;
            }
        }
        
        public WinButton UIButton1Button
        {
            get
            {
                if ((this.mUIButton1Button == null))
                {
                    this.mUIButton1Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIButton1Button.SearchProperties[WinButton.PropertyNames.Name] = "button1";
                    this.mUIButton1Button.WindowTitles.Add("XtraForm1");
                    #endregion
                }
                return this.mUIButton1Button;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBox1Edit;
        
        private WinEdit mUITextBox2Edit;
        
        private WinButton mUIButton1Button;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Desktop 1";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow1 mUIItemWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            #endregion
        }
        
        #region Properties
        public WinControl UIItemDialog
        {
            get
            {
                if ((this.mUIItemDialog == null))
                {
                    this.mUIItemDialog = new WinControl(this);
                    #region Search Criteria
                    this.mUIItemDialog.SearchProperties[UITestControl.PropertyNames.ControlType] = "Dialog";
                    #endregion
                }
                return this.mUIItemDialog;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIItemDialog;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "OK";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("OK");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("OK");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIForm1Window : WinWindow
    {
        
        public UIForm1Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Form1";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public UITextBox1Window UITextBox1Window
        {
            get
            {
                if ((this.mUITextBox1Window == null))
                {
                    this.mUITextBox1Window = new UITextBox1Window(this);
                }
                return this.mUITextBox1Window;
            }
        }
        
        public UITextBox2Window UITextBox2Window
        {
            get
            {
                if ((this.mUITextBox2Window == null))
                {
                    this.mUITextBox2Window = new UITextBox2Window(this);
                }
                return this.mUITextBox2Window;
            }
        }
        
        public UIButton1Window UIButton1Window
        {
            get
            {
                if ((this.mUIButton1Window == null))
                {
                    this.mUIButton1Window = new UIButton1Window(this);
                }
                return this.mUIButton1Window;
            }
        }
        #endregion
        
        #region Fields
        private UITextBox1Window mUITextBox1Window;
        
        private UITextBox2Window mUITextBox2Window;
        
        private UIButton1Window mUIButton1Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UITextBox1Window : WinWindow
    {
        
        public UITextBox1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBox1";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBox1Edit
        {
            get
            {
                if ((this.mUITextBox1Edit == null))
                {
                    this.mUITextBox1Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITextBox1Edit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBox1Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBox1Edit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UITextBox2Window : WinWindow
    {
        
        public UITextBox2Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBox2";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBox2Edit
        {
            get
            {
                if ((this.mUITextBox2Edit == null))
                {
                    this.mUITextBox2Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITextBox2Edit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBox2Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBox2Edit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIButton1Window : WinWindow
    {
        
        public UIButton1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button1";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UIButton1Button
        {
            get
            {
                if ((this.mUIButton1Button == null))
                {
                    this.mUIButton1Button = new WinButton(this);
                    #region Search Criteria
                    this.mUIButton1Button.SearchProperties[WinButton.PropertyNames.Name] = "button1";
                    this.mUIButton1Button.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIButton1Button;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIButton1Button;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UISignintoShopApplicatWindow : DXWindow
    {
        
        public UISignintoShopApplicatWindow()
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "Sign in to Shop Application";
            this.SearchProperties.Add(new PropertyExpression(DXTestControl.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Sign in to Shop Application");
            #endregion
        }
        
        #region Properties
        public UITablePanel1Client1 UITablePanel1Client
        {
            get
            {
                if ((this.mUITablePanel1Client == null))
                {
                    this.mUITablePanel1Client = new UITablePanel1Client1(this);
                }
                return this.mUITablePanel1Client;
            }
        }
        #endregion
        
        #region Fields
        private UITablePanel1Client1 mUITablePanel1Client;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UITablePanel1Client1 : DXTestControl
    {
        
        public UITablePanel1Client1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "tablePanel1";
            this.SearchProperties[DXTestControl.PropertyNames.ClassName] = "TablePanel";
            this.WindowTitles.Add("Sign in to Shop Application");
            #endregion
        }
        
        #region Properties
        public DXTextEdit UITxtNameEdit
        {
            get
            {
                if ((this.mUITxtNameEdit == null))
                {
                    this.mUITxtNameEdit = new DXTextEdit(this);
                    #region Search Criteria
                    this.mUITxtNameEdit.SearchProperties[DXTestControl.PropertyNames.Name] = "txtName";
                    this.mUITxtNameEdit.SearchProperties[DXTestControl.PropertyNames.ClassName] = "TextEdit";
                    this.mUITxtNameEdit.WindowTitles.Add("Sign in to Shop Application");
                    #endregion
                }
                return this.mUITxtNameEdit;
            }
        }
        
        public DXTextEdit UITxtPassEdit
        {
            get
            {
                if ((this.mUITxtPassEdit == null))
                {
                    this.mUITxtPassEdit = new DXTextEdit(this);
                    #region Search Criteria
                    this.mUITxtPassEdit.SearchProperties[DXTestControl.PropertyNames.Name] = "txtPass";
                    this.mUITxtPassEdit.SearchProperties[DXTestControl.PropertyNames.ClassName] = "TextEdit";
                    this.mUITxtPassEdit.WindowTitles.Add("Sign in to Shop Application");
                    #endregion
                }
                return this.mUITxtPassEdit;
            }
        }
        
        public DXButton UILOGINButton
        {
            get
            {
                if ((this.mUILOGINButton == null))
                {
                    this.mUILOGINButton = new DXButton(this);
                    #region Search Criteria
                    this.mUILOGINButton.SearchProperties[DXTestControl.PropertyNames.Name] = "btnLogin";
                    this.mUILOGINButton.SearchProperties[DXTestControl.PropertyNames.ClassName] = "SimpleButton";
                    this.mUILOGINButton.WindowTitles.Add("Sign in to Shop Application");
                    #endregion
                }
                return this.mUILOGINButton;
            }
        }
        
        public DXCheckBox UICheckEdit1CheckBox
        {
            get
            {
                if ((this.mUICheckEdit1CheckBox == null))
                {
                    this.mUICheckEdit1CheckBox = new DXCheckBox(this);
                    #region Search Criteria
                    this.mUICheckEdit1CheckBox.SearchProperties[DXTestControl.PropertyNames.Name] = "checkEdit1";
                    this.mUICheckEdit1CheckBox.SearchProperties[DXTestControl.PropertyNames.ClassName] = "CheckEdit";
                    this.mUICheckEdit1CheckBox.WindowTitles.Add("Sign in to Shop Application");
                    #endregion
                }
                return this.mUICheckEdit1CheckBox;
            }
        }
        
        public DXTestControl UILabelControl3Label
        {
            get
            {
                if ((this.mUILabelControl3Label == null))
                {
                    this.mUILabelControl3Label = new DXTestControl(this);
                    #region Search Criteria
                    this.mUILabelControl3Label.SearchProperties[DXTestControl.PropertyNames.Name] = "labelControl3";
                    this.mUILabelControl3Label.SearchProperties[DXTestControl.PropertyNames.ClassName] = "LabelControl";
                    this.mUILabelControl3Label.WindowTitles.Add("Sign in to Shop Application");
                    #endregion
                }
                return this.mUILabelControl3Label;
            }
        }
        #endregion
        
        #region Fields
        private DXTextEdit mUITxtNameEdit;
        
        private DXTextEdit mUITxtPassEdit;
        
        private DXButton mUILOGINButton;
        
        private DXCheckBox mUICheckEdit1CheckBox;
        
        private DXTestControl mUILabelControl3Label;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UINhom8_KDPM_PhanMemQuWindow : WpfWindow
    {
        
        public UINhom8_KDPM_PhanMemQuWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Nhom8_KDPM_PhanMemQuanLyShopQuanAo (Debugging) - Microsoft Visual Studio (Adminis" +
                "trator)";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Nhom8_KDPM_PhanMemQuanLyShopQuanAo (Debugging) - Microsoft Visual Studio (Adminis" +
                    "trator)");
            this.WindowTitles.Add("Nhom8_KDPM_PhanMemQuanLyShopQuanAo (Running) - Microsoft Visual Studio (Administr" +
                    "ator)");
            #endregion
        }
        
        #region Properties
        public UIItemTabList UIItemTabList
        {
            get
            {
                if ((this.mUIItemTabList == null))
                {
                    this.mUIItemTabList = new UIItemTabList(this);
                }
                return this.mUIItemTabList;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTabList mUIItemTabList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIItemTabList : WpfTabList
    {
        
        public UIItemTabList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Nhom8_KDPM_PhanMemQuanLyShopQuanAo (Debugging) - Microsoft Visual Studio (Adminis" +
                    "trator)");
            this.WindowTitles.Add("Nhom8_KDPM_PhanMemQuanLyShopQuanAo (Running) - Microsoft Visual Studio (Administr" +
                    "ator)");
            #endregion
        }
        
        #region Properties
        public UIWpfTextViewHostCustom UIWpfTextViewHostCustom
        {
            get
            {
                if ((this.mUIWpfTextViewHostCustom == null))
                {
                    this.mUIWpfTextViewHostCustom = new UIWpfTextViewHostCustom(this);
                }
                return this.mUIWpfTextViewHostCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIWpfTextViewHostCustom mUIWpfTextViewHostCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIWpfTextViewHostCustom : WpfCustom
    {
        
        public UIWpfTextViewHostCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = null;
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "WpfTextViewHost";
            this.WindowTitles.Add("Nhom8_KDPM_PhanMemQuanLyShopQuanAo (Debugging) - Microsoft Visual Studio (Adminis" +
                    "trator)");
            this.WindowTitles.Add("Nhom8_KDPM_PhanMemQuanLyShopQuanAo (Running) - Microsoft Visual Studio (Administr" +
                    "ator)");
            #endregion
        }
        
        #region Properties
        public WpfEdit UITextEditorEdit
        {
            get
            {
                if ((this.mUITextEditorEdit == null))
                {
                    this.mUITextEditorEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITextEditorEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "WpfTextView";
                    this.mUITextEditorEdit.WindowTitles.Add("Nhom8_KDPM_PhanMemQuanLyShopQuanAo (Debugging) - Microsoft Visual Studio (Adminis" +
                            "trator)");
                    #endregion
                }
                return this.mUITextEditorEdit;
            }
        }
        
        public UIGlyphMarginGridPane UIGlyphMarginGridPane
        {
            get
            {
                if ((this.mUIGlyphMarginGridPane == null))
                {
                    this.mUIGlyphMarginGridPane = new UIGlyphMarginGridPane(this);
                }
                return this.mUIGlyphMarginGridPane;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUITextEditorEdit;
        
        private UIGlyphMarginGridPane mUIGlyphMarginGridPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIGlyphMarginGridPane : WpfPane
    {
        
        public UIGlyphMarginGridPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfPane.PropertyNames.ClassName] = "Uia.GlyphMarginGrid";
            this.SearchProperties[WpfPane.PropertyNames.AutomationId] = "WpfEditorUIGlyphMarginGrid";
            this.WindowTitles.Add("Nhom8_KDPM_PhanMemQuanLyShopQuanAo (Running) - Microsoft Visual Studio (Administr" +
                    "ator)");
            #endregion
        }
        
        #region Properties
        public WpfImage UIBreakpointEnabledImage
        {
            get
            {
                if ((this.mUIBreakpointEnabledImage == null))
                {
                    this.mUIBreakpointEnabledImage = new WpfImage(this);
                    #region Search Criteria
                    this.mUIBreakpointEnabledImage.SearchProperties[WpfImage.PropertyNames.Name] = "Breakpoint (Enabled)";
                    this.mUIBreakpointEnabledImage.WindowTitles.Add("Nhom8_KDPM_PhanMemQuanLyShopQuanAo (Running) - Microsoft Visual Studio (Administr" +
                            "ator)");
                    #endregion
                }
                return this.mUIBreakpointEnabledImage;
            }
        }
        #endregion
        
        #region Fields
        private WpfImage mUIBreakpointEnabledImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIFormTNWindow : DXWindow
    {
        
        public UIFormTNWindow()
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "FormTN";
            this.SearchProperties.Add(new PropertyExpression(DXTestControl.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("FormTN");
            #endregion
        }
        
        #region Properties
        public UIAccordionControlContAccordionControl UIAccordionControlContAccordionControl
        {
            get
            {
                if ((this.mUIAccordionControlContAccordionControl == null))
                {
                    this.mUIAccordionControlContAccordionControl = new UIAccordionControlContAccordionControl(this);
                }
                return this.mUIAccordionControlContAccordionControl;
            }
        }
        #endregion
        
        #region Fields
        private UIAccordionControlContAccordionControl mUIAccordionControlContAccordionControl;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIAccordionControlContAccordionControl : DXTestControl
    {
        
        public UIAccordionControlContAccordionControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "accordionControlContainer";
            this.SearchProperties[DXTestControl.PropertyNames.ClassName] = "AccordionControl";
            this.WindowTitles.Add("FormTN");
            #endregion
        }
        
        #region Properties
        public DXTestControl UILOGOUTAccordionControlGroup
        {
            get
            {
                if ((this.mUILOGOUTAccordionControlGroup == null))
                {
                    this.mUILOGOUTAccordionControlGroup = new DXTestControl(this);
                    #region Search Criteria
                    this.mUILOGOUTAccordionControlGroup.SearchProperties[DXTestControl.PropertyNames.Name] = "LOG OUT";
                    this.mUILOGOUTAccordionControlGroup.SearchProperties[DXTestControl.PropertyNames.ClassName] = "AccordionControlGroup";
                    this.mUILOGOUTAccordionControlGroup.WindowTitles.Add("FormTN");
                    #endregion
                }
                return this.mUILOGOUTAccordionControlGroup;
            }
        }
        #endregion
        
        #region Fields
        private DXTestControl mUILOGOUTAccordionControlGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UILOGOUTWindow : WinWindow
    {
        
        public UILOGOUTWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "LOG OUT";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("LOG OUT");
            #endregion
        }
        
        #region Properties
        public UIYesWindow UIYesWindow
        {
            get
            {
                if ((this.mUIYesWindow == null))
                {
                    this.mUIYesWindow = new UIYesWindow(this);
                }
                return this.mUIYesWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIYesWindow mUIYesWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIYesWindow : WinWindow
    {
        
        public UIYesWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "6";
            this.WindowTitles.Add("LOG OUT");
            #endregion
        }
        
        #region Properties
        public WinButton UIYesButton
        {
            get
            {
                if ((this.mUIYesButton == null))
                {
                    this.mUIYesButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIYesButton.SearchProperties[WinButton.PropertyNames.Name] = "Yes";
                    this.mUIYesButton.WindowTitles.Add("LOG OUT");
                    #endregion
                }
                return this.mUIYesButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIYesButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIERRORWindow : WinWindow
    {
        
        public UIERRORWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ERROR";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("ERROR");
            #endregion
        }
        
        #region Properties
        public UIOKWindow1 UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow1(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIOKWindow1 mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIOKWindow1 : WinWindow
    {
        
        public UIOKWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
            this.WindowTitles.Add("ERROR");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("ERROR");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIChàomừngWindow : WinWindow
    {
        
        public UIChàomừngWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Chào mừng";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Chào mừng");
            #endregion
        }
        
        #region Properties
        public UIOKWindow2 UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow2(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIOKWindow2 mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIOKWindow2 : WinWindow
    {
        
        public UIOKWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
            this.WindowTitles.Add("Chào mừng");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Chào mừng");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIFormForgetWindow : DXWindow
    {
        
        public UIFormForgetWindow()
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "FormForget";
            this.SearchProperties.Add(new PropertyExpression(DXTestControl.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("FormForget");
            #endregion
        }
        
        #region Properties
        public UITablePanel1Client2 UITablePanel1Client
        {
            get
            {
                if ((this.mUITablePanel1Client == null))
                {
                    this.mUITablePanel1Client = new UITablePanel1Client2(this);
                }
                return this.mUITablePanel1Client;
            }
        }
        #endregion
        
        #region Fields
        private UITablePanel1Client2 mUITablePanel1Client;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UITablePanel1Client2 : DXTestControl
    {
        
        public UITablePanel1Client2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[DXTestControl.PropertyNames.Name] = "tablePanel1";
            this.SearchProperties[DXTestControl.PropertyNames.ClassName] = "TablePanel";
            this.WindowTitles.Add("FormForget");
            #endregion
        }
        
        #region Properties
        public DXTextEdit UITxtNameEdit
        {
            get
            {
                if ((this.mUITxtNameEdit == null))
                {
                    this.mUITxtNameEdit = new DXTextEdit(this);
                    #region Search Criteria
                    this.mUITxtNameEdit.SearchProperties[DXTestControl.PropertyNames.Name] = "txtName";
                    this.mUITxtNameEdit.SearchProperties[DXTestControl.PropertyNames.ClassName] = "TextEdit";
                    this.mUITxtNameEdit.WindowTitles.Add("FormForget");
                    #endregion
                }
                return this.mUITxtNameEdit;
            }
        }
        
        public DXTextEdit UITxtPhoneEdit
        {
            get
            {
                if ((this.mUITxtPhoneEdit == null))
                {
                    this.mUITxtPhoneEdit = new DXTextEdit(this);
                    #region Search Criteria
                    this.mUITxtPhoneEdit.SearchProperties[DXTestControl.PropertyNames.Name] = "txtPhone";
                    this.mUITxtPhoneEdit.SearchProperties[DXTestControl.PropertyNames.ClassName] = "TextEdit";
                    this.mUITxtPhoneEdit.WindowTitles.Add("FormForget");
                    #endregion
                }
                return this.mUITxtPhoneEdit;
            }
        }
        
        public DXTextEdit UITxtEmailEdit
        {
            get
            {
                if ((this.mUITxtEmailEdit == null))
                {
                    this.mUITxtEmailEdit = new DXTextEdit(this);
                    #region Search Criteria
                    this.mUITxtEmailEdit.SearchProperties[DXTestControl.PropertyNames.Name] = "txtEmail";
                    this.mUITxtEmailEdit.SearchProperties[DXTestControl.PropertyNames.ClassName] = "TextEdit";
                    this.mUITxtEmailEdit.WindowTitles.Add("FormForget");
                    #endregion
                }
                return this.mUITxtEmailEdit;
            }
        }
        
        public DXButton UIAcceptButton
        {
            get
            {
                if ((this.mUIAcceptButton == null))
                {
                    this.mUIAcceptButton = new DXButton(this);
                    #region Search Criteria
                    this.mUIAcceptButton.SearchProperties[DXTestControl.PropertyNames.Name] = "btnAccept";
                    this.mUIAcceptButton.SearchProperties[DXTestControl.PropertyNames.ClassName] = "SimpleButton";
                    this.mUIAcceptButton.WindowTitles.Add("FormForget");
                    #endregion
                }
                return this.mUIAcceptButton;
            }
        }
        
        public DXTestControl UILbPassLabel
        {
            get
            {
                if ((this.mUILbPassLabel == null))
                {
                    this.mUILbPassLabel = new DXTestControl(this);
                    #region Search Criteria
                    this.mUILbPassLabel.SearchProperties[DXTestControl.PropertyNames.Name] = "lbPass";
                    this.mUILbPassLabel.SearchProperties[DXTestControl.PropertyNames.ClassName] = "LabelControl";
                    this.mUILbPassLabel.WindowTitles.Add("FormForget");
                    #endregion
                }
                return this.mUILbPassLabel;
            }
        }
        #endregion
        
        #region Fields
        private DXTextEdit mUITxtNameEdit;
        
        private DXTextEdit mUITxtPhoneEdit;
        
        private DXTextEdit mUITxtEmailEdit;
        
        private DXButton mUIAcceptButton;
        
        private DXTestControl mUILbPassLabel;
        #endregion
    }
}
