using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using BLL_DAL;
namespace GUI.V_BaoHanh
{
    public partial class UserControls_DSPhieuBaoHanh : DevExpress.XtraEditors.XtraUserControl
    {
        BaoHanh_BLLDAL BaoHanh_BLLDAL = new BaoHanh_BLLDAL();
        public UserControls_DSPhieuBaoHanh()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard

            // This line of code is generated by Data Source Configuration Wizard
            bAOHANHsBindingSource.DataSource = new BLL_DAL.QLShopDataContext().BAOHANHs;
        }

        private void panel2_Paint(object sender, PaintEventArgs e)
        {

        }

        private void UserControls_DSPhieuBaoHanh_Load(object sender, EventArgs e)
        {
            bAOHANHsBindingSource.DataSource = new BLL_DAL.QLShopDataContext().BAOHANHs.Where(t=>t.TRANGTHAI== "Đang bảo hành");
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void gridControl1_Click_1(object sender, EventArgs e)
        {
              int maPHBH  = int.Parse(gridView1.GetFocusedRowCellValue("MAPHIEUBH").ToString());
            label2.Text = "Khách Hàng: " + BaoHanh_BLLDAL.timKH(maPHBH).TENKHACHHANG;
        }

        private void repositoryItemButtonEdit1_Click(object sender, EventArgs e)
        {
            if (MessageBox.Show("Bạn có chắc sản phẩm này đã bảo hành xong?", "Question?", MessageBoxButtons.YesNo) == DialogResult.Yes)
            {
                int maPHBH = int.Parse(gridView1.GetFocusedRowCellValue("MAPHIEUBH").ToString());
                BaoHanh_BLLDAL.daBaoHanhXong(maPHBH);
                MessageBox.Show("Bảo hành thành công!");
            }
        }
    }
}
