using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using BLL_DAL;

namespace GUI.V_BaoHanh
{
    public partial class UserControl_LapPhieuBH : DevExpress.XtraEditors.XtraUserControl
    {
         CTHD_BLLDAL CTHD_BLLDAL = new CTHD_BLLDAL();
        BaoHanh_BLLDAL BaoHanh_BLLDAL = new BaoHanh_BLLDAL();
        List<string> lyDo = new List<string>();

        public UserControl_LapPhieuBH()
        {
            InitializeComponent();
            Load_DL();
        }

        public void Load_DL()
        {
            // This line of code is generated by Data Source Configuration Wizard
            hOADONsBindingSource.DataSource = new BLL_DAL.QLShopDataContext().HOADONs;
            // This line of code is generated by Data Source Configuration Wizard
            cHITIETHOADONsBindingSource.DataSource = new BLL_DAL.QLShopDataContext().CHITIETHOADONs;
            gridControl3.DataSource = Program.dsBaoHanh.ToList();
        }
        private void UserControl_LapPhieuNhap_Load(object sender, EventArgs e)
        {

        }

        private void panel5_Paint(object sender, PaintEventArgs e)
        {

        }

        private void gridControl1_Click(object sender, EventArgs e)
        {
            if (Program.dsBaoHanh.Count != 0)
            {
                if (MessageBox.Show("Bạn đang chọn hóa đơn khác!\nBạn có muốn HỦY DS bảo hành đang tạo?", "Warning", MessageBoxButtons.YesNo) == DialogResult.Yes)
                {
                    var listCTHD = BaoHanh_BLLDAL.listCtHD(int.Parse(gridView1.GetFocusedRowCellValue("MAHOADON").ToString()));
                    gridControl2.DataSource = listCTHD;
                    Program.dsBaoHanh.Clear();
                    gridControl3.DataSource = null;
                    return;
                }
            }
            else {
                var listCTHD = BaoHanh_BLLDAL.listCtHD(int.Parse(gridView1.GetFocusedRowCellValue("MAHOADON").ToString()));
                gridControl2.DataSource = listCTHD;
            }
          
        }

        private void panel2_Paint(object sender, PaintEventArgs e)
        {

        }

        private void gridControl3_Click(object sender, EventArgs e)
        {

        }

        private void gridControl2_Click(object sender, EventArgs e)
        {

        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            //kiem tra ly do
            if(txtLyDo.Text=="")
            {
                MessageBox.Show("Vui lòng nhập lý do bảo hành!");
                return;
            }    
            //kiemtraDS
            int mactHD = int.Parse(gridView2.GetFocusedRowCellValue("MACHITIETHD").ToString());
            foreach(var item in Program.dsBaoHanh)
            {
                if(mactHD==item.MACHITIETHD)
                {
                    MessageBox.Show("Sản phẩm này đã được thêm vào danh sách bảo hành");
                    return;
                }    
            }  
            //them vào ds Bảo hành
            try
            {
                CHITIETHOADON cthd = CTHD_BLLDAL.CTHD(mactHD);
                CHITIETBAOHANH CTBH = new CHITIETBAOHANH();
                CTBH.MACHITIETHD = mactHD;
                lyDo.Add(mactHD + "--" + txtLyDo.Text +"\n");
                txtLyDo.Text = "";
                Program.dsBaoHanh.Add(cthd);
                Load_DL();
            }
            catch
            {
                MessageBox.Show("Vui lòng chọn sản phẩm cần bảo hành!");
            }
           
            


        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            if(Program.dsBaoHanh.Count==0)
            {
                MessageBox.Show("Phiếu Bảo Hành Rỗng");
                return;
            }    
            if (MessageBox.Show("Đồng ý tạo phiếu bảo hành này?", "Question?", MessageBoxButtons.YesNo) == DialogResult.Yes)
            {
                BaoHanh_BLLDAL.luuPhieuBaoHanh(Program.dsBaoHanh, lyDo);
                MessageBox.Show("Đã lưu thành công!");
                using (Reporting.frmPrint frmPrint = new Reporting.frmPrint())
                {
                    frmPrint.PrintPhieuBaoHanh(BaoHanh_BLLDAL.getMaPNMoi().MAPHIEUBH);
                    frmPrint.ShowDialog();
                }
            }
        }
    }
}
